/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ElevenLabs editorial tokens
        ink: '#0c0a09',
        'ink-active': '#292524',
        canvas: '#f5f5f5',
        'canvas-soft': '#fafafa',
        'canvas-deep': '#0c0a09',
        'surface-card': '#ffffff',
        'surface-strong': '#f0efed',
        'surface-dark': '#0c0a09',
        'surface-dark-elevated': '#1c1917',
        body: '#4e4e4e',
        'body-strong': '#292524',
        muted: '#777169',
        'muted-soft': '#a8a29e',
        hairline: '#e7e5e4',
        'hairline-soft': '#f0efed',
        'hairline-strong': '#d6d3d1',
        'on-ink': '#ffffff',
        'on-dark': '#ffffff',
        'on-dark-soft': '#a8a29e',
        'gradient-mint': '#a7e5d3',
        'gradient-peach': '#f4c5a8',
        'gradient-lavender': '#c8b8e0',
        'gradient-sky': '#a8c8e8',
        'gradient-rose': '#e8b8c4',
        'semantic-error': '#dc2626',
        'semantic-success': '#16a34a',

        // Legacy tokens remapped so existing utility classes retheme automatically
        'on-tertiary-container': '#a8a29e',
        'surface-container-low': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container': '#ffffff',
        'on-tertiary-fixed': '#0c0a09',
        'surface-container-lowest': '#fafafa',
        'tertiary-fixed-dim': '#c8b8e0',
        'on-tertiary': '#0c0a09',
        'on-tertiary-fixed-variant': '#777169',
        'neon-lime': '#0c0a09',
        'tertiary-container': '#f0efed',
        'surface-tint': '#0c0a09',
        'surface-container-highest': '#f0efed',
        'surface-variant': '#f0efed',
        secondary: '#777169',
        'inverse-primary': '#f5f5f5',
        'border-subtle': '#e7e5e4',
        'error-container': '#fee2e2',
        'on-primary-fixed': '#ffffff',
        outline: '#d6d3d1',
        'on-error-container': '#dc2626',
        primary: '#0c0a09',
        'on-primary-container': '#ffffff',
        'surface-bright': '#ffffff',
        'surface-deep': '#f5f5f5',
        background: '#f5f5f5',
        'surface-container-high': '#f0efed',
        'surface-dim': '#f5f5f5',
        'on-surface-variant': '#4e4e4e',
        'inverse-on-surface': '#f5f5f5',
        'surface-elevated': '#ffffff',
        'on-secondary-fixed': '#ffffff',
        'secondary-fixed': '#f0efed',
        'on-secondary': '#0c0a09',
        tertiary: '#0c0a09',
        'outline-variant': '#e7e5e4',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#777169',
        'on-secondary-fixed-variant': '#777169',
        'on-surface': '#0c0a09',
        'primary-container': '#0c0a09',
        surface: '#f5f5f5',
        'secondary-fixed-dim': '#a8a29e',
        'secondary-container': '#f0efed',
        'primary-fixed': '#0c0a09',
        'inverse-surface': '#0c0a09',
        'on-secondary-container': '#4e4e4e',
        error: '#dc2626',
        'on-background': '#0c0a09',
        'tertiary-fixed': '#f0efed',
        'primary-fixed-dim': '#292524',
        'velocity-purple': '#c8b8e0',
        'velocity-blue': '#a8c8e8',
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '6px',
        DEFAULT: '8px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        xxl: '24px',
        pill: '9999px',
        full: '9999px',
      },
      spacing: {
        'container-max': '1200px',
        'stack-sm': '12px',
        'stack-lg': '32px',
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '80px',
        'stack-md': '20px',
        'section-v-space': '96px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'headline-display-mobile': ['"EB Garamond"', 'serif'],
        'headline-display': ['"EB Garamond"', 'serif'],
        'label-mono': ['Inter', 'sans-serif'],
        'italic-accent': ['"EB Garamond"', 'serif'],
        'headline-md': ['"EB Garamond"', 'serif'],
        'headline-lg': ['"EB Garamond"', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        display: ['"EB Garamond"', '"Times New Roman"', 'serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.44', letterSpacing: '0.18px', fontWeight: '500' }],
        'headline-display-mobile': ['40px', { lineHeight: '1.1', letterSpacing: '-0.8px', fontWeight: '300' }],
        'headline-display': ['64px', { lineHeight: '1.05', letterSpacing: '-1.92px', fontWeight: '300' }],
        'label-mono': ['12px', { lineHeight: '1.4', letterSpacing: '0.96px', fontWeight: '600' }],
        'italic-accent': ['inherit', { fontWeight: '400', fontStyle: 'italic' }],
        'headline-md': ['32px', { lineHeight: '1.13', letterSpacing: '-0.32px', fontWeight: '300' }],
        'headline-lg': ['36px', { lineHeight: '1.17', letterSpacing: '-0.36px', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0.16px', fontWeight: '400' }],
        'display-xl': ['48px', { lineHeight: '1.08', letterSpacing: '-0.96px', fontWeight: '300' }],
        'display-sm': ['24px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '300' }],
        'title-md': ['20px', { lineHeight: '1.35', letterSpacing: '0', fontWeight: '500' }],
        caption: ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
